version: '3.2'
services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
          - 9090:9090
        restart: always
        depends_on:
            - alertmanager

    alertmanager-bot:
        command:
        - --alertmanager.url=http://alertmanager:9093
        - --log.level=info
        - --store=bolt
        - --bolt.path=/data/bot.db
        environment:
          TELEGRAM_ADMIN: "number_id_chat"
          TELEGRAM_TOKEN: api_token
        image: metalmatze/alertmanager-bot
        ports:
        - 8080:8080
        restart: always
        volumes:
        - ./data:/data/


    alertmanager:
       image: prom/alertmanager
       container_name: alertmanager
       volumes:
         - ./alertmanager:/etc/alertmanager/data/
         - ./alertmanager:/etc/alertmanager/
       command:
         - '--config.file=/etc/alertmanager/config.yml'
         - '--storage.path=/etc/alertmanager/data'
       ports:
         - 9093:9093
       restart: always

    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        hostname: monitoring
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
          - 9100:9100
        restart: always

    grafana:
      image: grafana/grafana:8.4.4
      depends_on:
        - prometheus
      container_name: grafana
      ports:
        - 3000:3000
      volumes:
        - ./grafana_data/var/lib/grafana
        - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      environment:
        - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
        - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
        - GF_USERS_ALLOW_SIGN_UP=false
      restart: always
      expose:
        - 3000

    blackbox-exporter:
      image: prom/blackbox-exporter:latest
      volumes:
        - ./blackbox/blackbox.yml:/config/blackbox.yml
      command:
        - '--config.file=/config/blackbox.yml'
      restart: unless-stopped
      ports:
        - "9115:9115"